
#ifndef _PARSER_H_
#define _PARSER_H_

#include "ast.h"

ast_module_t* parse_module(void);
ast_module_item_t* parse_module_item(void);
ast_start_definition_t* parse_start_definition(void);
ast_import_statement_t* parse_import_statement(void);
ast_include_statement_t* parse_include_statement(void);
ast_namespace_item_t* parse_namespace_item(void);
ast_scope_operator_t* parse_scope_operator(void);
ast_literal_type_name_t* parse_literal_type_name(void);
ast_type_name_t* parse_type_name(void);
ast_type_name_list_t* parse_type_name_list(void);
ast_formatted_strg_t* parse_formatted_strg(void);
ast_string_literal_t* parse_string_literal(void);
ast_literal_value_t* parse_literal_value(void);
ast_var_decl_t* parse_var_decl(void);
ast_var_decl_list_t* parse_var_decl_list(void);
ast_function_assignment_t* parse_function_assignment(void);
ast_assignment_item_t* parse_assignment_item(void);
ast_var_definition_t* parse_var_definition(void);
ast_list_init_str_t* parse_list_init_str(void);
ast_list_init_element_t* parse_list_init_element(void);
ast_list_init_t* parse_list_init(void);
ast_array_param_item_t* parse_array_param_item(void);
ast_array_param_t* parse_array_param(void);
ast_array_param_list_t* parse_array_param_list(void);
ast_array_reference_t* parse_array_reference(void);
ast_function_reference_t* parse_function_reference(void);
ast_create_reference_t* parse_create_reference(void);
ast_destroy_reference_t* parse_destroy_reference(void);
ast_compound_name_t* parse_compound_name(void);
ast_compound_name_list_t* parse_compound_name_list(void);
ast_compound_ref_item_t* parse_compound_ref_item(void);
ast_compound_reference_t* parse_compound_reference(void);
ast_cast_statement_t* parse_cast_statement(void);
ast_expression_t* parse_expression(void);
ast_expr_or_t* parse_expr_or(void);
ast_expr_and_t* parse_expr_and(void);
ast_expr_equality_t* parse_expr_equality(void);
ast_expr_compare_t* parse_expr_compare(void);
ast_expr_term_t* parse_expr_term(void);
ast_expr_factor_t* parse_expr_factor(void);
ast_expr_unary_t* parse_expr_unary(void);
ast_expr_primary_t* parse_expr_primary(void);
ast_expression_list_t* parse_expression_list(void);
ast_namespace_definition_t* parse_namespace_definition(void);
ast_class_definition_t* parse_class_definition(void);
ast_class_item_t* parse_class_item(void);
ast_function_declaration_t* parse_function_declaration(void);
ast_create_declaration_t* parse_create_declaration(void);
ast_destroy_declaration_t* parse_destroy_declaration(void);
ast_function_definition_t* parse_function_definition(void);
ast_create_name_t* parse_create_name(void);
ast_create_definition_t* parse_create_definition(void);
ast_destroy_name_t* parse_destroy_name(void);
ast_destroy_definition_t* parse_destroy_definition(void);
ast_function_body_t* parse_function_body(void);
ast_assign_eq_item_t* parse_assign_eq_item(void);
ast_assign_inc_item_t* parse_assign_inc_item(void);
ast_assignment_t* parse_assignment(void);
ast_function_body_element_t* parse_function_body_element(void);
ast_break_statement_t* parse_break_statement(void);
ast_continue_statement_t* parse_continue_statement(void);
ast_yield_statement_t* parse_yield_statement(void);
ast_type_statement_t* parse_type_statement(void);
ast_return_statement_t* parse_return_statement(void);
ast_raise_statement_t* parse_raise_statement(void);
ast_trace_statement_t* parse_trace_statement(void);
ast_print_statement_t* parse_print_statement(void);
ast_exit_statement_t* parse_exit_statement(void);
ast_while_definition_t* parse_while_definition(void);
ast_while_clause_t* parse_while_clause(void);
ast_do_clause_t* parse_do_clause(void);
ast_for_clause_t* parse_for_clause(void);
ast_if_clause_t* parse_if_clause(void);
ast_else_clause_t* parse_else_clause(void);
ast_final_else_clause_t* parse_final_else_clause(void);
ast_try_clause_t* parse_try_clause(void);
ast_except_clause_t* parse_except_clause(void);
ast_final_clause_t* parse_final_clause(void);

void recover_error(void);
AstNode* parse(void);


#endif /* _PARSER_H_ */

